### ISSUE TITLE
'Set Timer from Delay' error

### ISSUE THREAD

**Issue by damomato** [TheNoctambulist/hass-airtouch#20]
### System Health details

.

### Checklist

- [x] I have enabled debug logging for the integration.
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Hi, thanks for the great integration. I'm trying to make a button to set a 15 minute timer but keep getting this error when triggering the action:

`Failed to perform the action airtouch/set_timer_from_delay. QuickTimerEncoder.encode() got an unexpected keyword argument 'header'`

I seem to be able to manually set the on timer in the entity, just not through the off timer. The action doesn't seem to work for either.

Any help is much appreciated.

### Reproduction steps

1..
2.
3.
...

### Debug logs

```Text
.
```

**Comment by TheNoctambulist** [comment]
Thanks for the error report. I think I will be able to find the problem from that error message. I'll let you know once I have published a new version with the fix

**Comment by damomato** [comment]
Thanks! Sorry I was pretty tired when I submitted this so forgot some details.

I'm using an AirTouch4 on latest version 1.4.4. I may just be terrible at home assistant and not sure how to set a timer properly, but hopefully it's not that and instead it's a simple big which can be fixed.

**Comment by TheNoctambulist** [comment]
@damomato I've published a v1.5.2 update which should fix this. Let me know how it goes.

**Comment by damomato** [comment]
Hi thanks for sorting this so fast! I'm getting no more error messages, however I'm still experiencing a couple of issues

Setting and clearing the On Timer seems to be working completely fine now. 

Setting the Off Timer, however, appears to be working (as the timer icon seems to appear on the airtouch4 app) but the off timer entity state in HA remains as 'Unknown' and therefore the off timer can't be cleared.

**Comment by TheNoctambulist** [comment]
Thanks for testing. I don't have an AirTouch 4 so it's harder to avoid bugs in this area!
Are you able to turn on debug logging for the integration, then set an off timer? That should help me to see what's going on.

I'll take a look at the timer status logic to see if there's anything obvious, but the debug logs would be helpful.

**Comment by TheNoctambulist** [comment]
I think I found the error from when I reverse engineered the timer status message. I've release v1.5.3 with some updates that should fix the off timer.

**Comment by damomato** [comment]
Thanks! I didn't have time to trace the bug as mentioned in your earlier comment so glad you worked it out :)

Just tested it and looks to be working with one slight bug. When I set a timer, for example for 15 mins, the state puts it in as an 18 minute timer (time showing 18 mins head instead of 15 mins ahead). But according to the entity history the aircon still stops after 15 minutes like it's supposed to.

So it's working and I don't really have an issue with that other bug, so thanks for all your work on this!

**Comment by TheNoctambulist** [comment]
Thanks for letting me know. 

That time difference sounds like either your AirTouch console or Home Assistant client (or possibly server) might be out of time sync. If it's a few minutes out you should be able to see it by just comparing the clocks between your devices.

**Comment by damomato** [comment]
Good idea I'll dig around. Thanks

**Comment by damomato** [comment]
You were right, my aircon clock is set 4 minutes ahead to the actual time. Easy fix!

**Comment by TheNoctambulist** [comment]
Excellent. Glad to hear it's all sorted
